### ISSUE TITLE
高效王国有问题，不能使用

### ISSUE THREAD

**Issue by mysq1isworst** [legendaryhero1981/Dear-Unity-Mod-Manager#3]
高效王国是N网的最新版本，尝试过了，原版umm最新版可以正常加载，换到dumm之后，加载一直显示有错误，怀疑是管理器版本问题。
求解决，谢谢

**Comment by legendaryhero1981** [comment]
UI空间名称冲突问题，最新的DUMM已保留UMM中的样式控件名称。
